### ISSUE TITLE
Reg fails with the phone from 'S'

### ISSUE THREAD

**Issue by reto271** [reto271/DoorStateByTelegram#7]
At the moment the reason is unknown. It seems that there is no from.first_name info. 

It might be because of the additional password he set in his Telegram account.

Current state in V01.06 B01:
- Additional log message added
- 'S' will again send a message, e.g. 'H'

**Comment by reto271** [comment]
Log showing the failure:

2020-10-02 16:21:26.951840 : -------------------------------------------
{u'date': 1601648486, u'text': u'H', u'from': {u'username': u'Seppi_L', u'first_name': u'Seppi L', u'is_bot': False, u'id': 1205315871, u'language_code': u'de'}, u'message_id': 646, u'chat': {u'username': u'Seppi_L', u'first_name': u'Seppi L', u'type': u'private', u'id': 1205315871}}
2020-10-02 16:21:26.952142 : {u'date': 1601648486, u'text': u'H', u'from': {u'username': u'Seppi_L', u'first_name': u'Seppi L', u'is_bot': False, u'id': 1205315871, u'language_code': u'de'}, u'message_id': 646, u'chat': {u'username': u'Seppi_L', u'first_name': u'Seppi L', u'type': u'private', u'id': 1205315871}}
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/telepot/__init__.py", line 1158, in collector
    callback(item)
  File "DoorStateUpdater.py", line 38, in handle
    m_debugLogger.logMessageWithUser(msg['from']['first_name'], msg['from']['last_name'], userId, command)
KeyError: 'last_name'
2020-10-02 16:24:58.999619 : -------------------------------------------

To compare a working request from Reto:

2020-10-02 16:25:54.490123 : -------------------------------------------
{u'date': 1601648754, u'text': u'H', u'from': {u'first_name': u'Reto', u'last_name': u'Duss', u'is_bot': False, u'id': 308764185, u'language_code': u'en'}, u'message_id': 657, u'chat': {u'first_name': u'Reto', u'last_name': u'Duss', u'type': u'private', u'id': 308764185}}
2020-10-02 16:25:54.490284 : {u'date': 1601648754, u'text': u'H', u'from': {u'first_name': u'Reto', u'last_name': u'Duss', u'is_bot': False, u'id': 308764185, u'language_code': u'en'}, u'message_id': 657, u'chat': {u'first_name': u'Reto', u'last_name': u'Duss', u'type': u'private', u'id': 308764185}}
2020-10-02 16:25:54.490324 [Reto Duss] 308764185 : H
2020-10-02 16:25:54.490368 : -------------------------------------------
